### ISSUE TITLE
todo-list refactor

### ISSUE THREAD

**Issue by fgerick** [fgerick/Limace.jl#7]
- [x] Remove precalculation of Jacobi polynomials. 
- [x] Create `Basis` structures to generalize
- [x] Write all multithreaded functions that integrate numerically.
- [ ] All BC generalizations.
- [ ] Get code coverage up.
- [x] Write documentation (not just autogenerated)
- [x] More complex example notebooks
- [x] Discretization functions (SHTns?)
- [ ] Postprocessing, energies, quality factors, categorizing
- [ ] Plotting
- [x] Volumes (Sphere, spherical shell)
